name: Run Sonar

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'
      - 'develop'
      - 'release/*'

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonarqube:
    name: Run Sonar Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Sonar
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar-projectKey=checkout_NetworkClient-iOS_AYhsdjYEfXz2nF6wDAnO
            -Dsonar.sources=.
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-
            -Dsonar.coverage.exclusions=Tests/**
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
