name: "Verify PR"

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-13-large

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Edited Files
        run: bash .github/scripts/lintEditedFiles.sh

  verify-pr:
    name: Verify PR
    runs-on: macos-14-xlarge
    needs: lint

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Select Xcode
      run: |
        sudo xcode-select -switch /Applications/Xcode_15.2.app

    - name: Log xcodebuild Version
      run: |
        xcodebuild -version

    - name: Build the Package
      run: |
        set -o pipefail && xcodebuild -scheme CheckoutNetwork -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest"

    - name: Run Tests
      run: |
        set -o pipefail && xcodebuild -scheme CheckoutNetwork -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" test
